### ISSUE TITLE
Commit when no changes results in walkback

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#317]
If you do a commit and git finds no changes, it puts up a walkback. 
It's not very friendly.  Some of us who like to commit "just in case".

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $GEMSTONE/TomatoProject4//Tomato4; git --git-dir $GEMSTONE/TomatoProject4//Tomato4/.git --work-tree $GEMSTONE/TomatoProject4//Tomato4 commit --file=/tmp/commitMessage' stdout: 'On branch master
nothing to commit, working directory clean
' failed with status: 256 errno: 0 errStr: nil

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitcommitIn:with: @2 line 3
RwPrjCommitTool (RwAbstractTool) >> doGitCommit: @11 line 8
RwGitRepositorySpecification >> commitForTool:message: @2 line 2
RwSimpleProjectSpecification (RwProjectSpecification) >> commitForTool:message: @3 line 2
RwPrjCommitTool >> commitProjectNamed:message: @18 line 16
RowanProjectService >> commitWithMessage: @7 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
I think this is a jadeite issue if not transfer back to Rowan...

**Comment by LisaAlmarode** [comment]
This still happens in 3.0.75.  Haven't been doing any git commits myself lately but it is still an alarming message.

**Comment by ericwinger** [comment]
Because the error occurs in rowan code, the best Jadeite can do is disable the ``Commit to Git ...`` menu item if the project is not dirty in both the project list & project browser. With luck, this will suffice. Fixed in 3.0.76.

**Comment by LisaAlmarode** [comment]
This is not fixed, since if you make a change and undo it, you will get the walkback. If Jadeite can't handle it, then it needs to go to Rowan.  It's pretty minor but it does need to get dealt with for some future GA release.

**Comment by LisaAlmarode** [comment]
The problem is that the commit to git will fail, if the on-disk state is the same as what was already in git.  The jadeite project could be dirty due to add and remove of a space, for example.

Can Jadeite detect if the on-disk files in the repository, that would be git-checked-in, actually has changes from what is already checked in?  If Jadeite can figure that out, it can enable/disable commits to avoid a walkback.  E.g., if Jadeite does a two-step process of write then commit, we could insert the query in between and only commit if there were changes.

If Rowan handles the write to disk and git commit within a single operation that jadeite invokes, then Rowan is going to have to do that query, or handle the error.  If that's too hard for Rowan to do, possible a new API method would be needed - Jadeite could do a write, query for changes, and then commit.

**Comment by dalehenrich** [comment]
@LisaAlmarode I don't know which version of Jadeite and Rowan you are looking at here, but in V3/V2.2, I think you should be getting a dialog that contains the message from the result of the commit ... if there was nothing to commit, you get a dialog telling you that there is nothing to commit ... I've got tests that handle the interaction request and check the message ... so I've guessing you are using an older version of Jadeite?

**Comment by LisaAlmarode** [comment]
As of 3.2.12, you first get: 
![image](https://user-images.githubusercontent.com/13142166/200663186-7cbe6c4e-0d2d-4433-ba1f-627e59c1ab10.png)
then you press OK, and get:
![image](https://user-images.githubusercontent.com/13142166/200663283-400bd739-f538-41fa-b9f5-11587b4948c4.png)

git log indicates it was not committed, so this second dialog is wrong.
However, it's better than a walkback.

**Comment by ericwinger** [comment]
If Rowan determines there is nothing to commit to git, it sends a client forwarder message back to the client. However, the client forwarder is handled at a low level so the rowan services code doesn't get to intercept it. In addition, Jadeite doesn't get notified that no commit happened because `RwPrjCommitTool>>commitProjectNamed:message:` doesn't return the result of the git commit. Filed https://github.com/GemTalk/Rowan/issues/887 to address.
